config/routes.rb
Redminer::Application.routes.draw do
  resources :issues

  resources :projects

end

app/models/issue.rb
class Issue < ActiveResource::Base
  Issue.site = '' # http://username:password@redmine-url.com
end

app/models/project.rb
class Project < ActiveResource::Base
  Project.site = '' # http://username:password@redmine-url.com
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.find(:all).sort_by(&:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @issues = Issue.find(:all, :params => { 
                           :project_id => params[:id] })
    @issues_today = Issue.find(:all, 
                               :params => {
                                 :project_id => params[:id],
                                 :limit => 100,
                                 :status_id => '*'},
                               :conditions => ['updated_on >= ? and updated_on < ?', Date.today(), Date.today()+1])
    @statuses = %w(Open New Closed Resolved)

                                 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redminer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
<h1><span id="red">Red</span>miner</h1>
</div>
<div id="page">
<%= yield %>
</div>
</body>
</html>

app/views/projects/.#_project.html.erb
steph@steph-laptop.440:1329507631

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :last_updated %><br />
    <%= f.date_select :last_updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<h2><%= @project.name %></h2>
<% unless @project.description.empty?%>
<p><%= @project.description %></p>
<% end %>

app/views/projects/_project_stat.html.erb
<h2><%= @project.name %></h2>
<% unless @project.description.empty?%>
<p><%= @project.description %></p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Last updated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= truncate(project.description, length:50) %></td>
    <td><%= Time.parse(project.updated_on).strftime("%b %d") %></td>
    <td><%= link_to 'Show', project %></td>
    <!-- <td><%= link_to 'Edit', edit_project_path(project) %></td> -->
    <!-- <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @project.name %></h2>
<% unless @project.description.empty?%>
<p><%= @project.description %></p>
<% end %>

<div id="stats">
  <h3>Today:</h3>
  <ul>
    <% @statuses.each do |status| %>
    <li><%= status %>: <span id="count"><%= @issues_today.find_all { |issue| issue.status.name == status}.count %></span></li>
    <% end %>
  </ul>
</div>

<h3>Last issues reported</h3>
<ul class="issues">
<% @issues.each do |issue| %>
<li class="<%= cycle('list_line_odd', 'list_line_even') %>">

<span class="bugid"><%= issue.id %></span><span class="title"><%= issue.subject %></span><span class="desc"><%= issue.description %></li>
<% end %>
</ul>
<%= link_to 'Back', projects_path %>